### ISSUE TITLE
Unable to add movies from list

### ISSUE THREAD

**Issue by sammykins12** [Radarr/RadarrAPI.TMDB#3]
When trying to import a large list e.g. https://api.radarr.video/v2/imdb/list?listId=ls000344406
API returns that it cannot find a movie named "
No indication in log as to what movie is causing this
Unable to find a movie incorrectly titled
Issue persists when using the IMDB RSS List or Radarr List for IMDB

Attached Radarr log that doesn't seem to indicate anything error-wise.

[radarr.txt](https://github.com/Radarr/RadarrAPI.TMDB/files/1132940/radarr.txt)

**Comment by galli-leo** [comment]
Is this still happening with the latest API? IIRC I have optimised loading lists heavily.
