### ISSUE TITLE
IMDB List Result Doesn't Include All Titles

### ISSUE THREAD

**Issue by RyanMathewson** [Radarr/RadarrAPI.TMDB#38]
I am trying to pull in this IMDB list but the API isn't returning all of the titles.
https://www.imdb.com/list/ls025843356/
https://api.radarr.video/v2/imdb/list?listId=ls025843356

Currently the IMDB list contains 623 titles but the API only returns 578 items.

**Comment by galli-leo** [comment]
The issue is likely that those movies are not on TMDB (or were added very recently to TMDB).

**Comment by RyanMathewson** [comment]
I don't think that is the case.  For example the movie "Pride, Prejudice
and Mistletoe" exists in the IMDB[0] list and on TMDB[1] but is not
returned in your API results [2].
[0] https://www.imdb.com/title/tt8634192/
[1]
https://www.themoviedb.org/movie/535810-pride-and-prejudice-and-mistletoe
[2] https://api.radarr.video/v2/imdb/list?listId=ls025843356

**Comment by galli-leo** [comment]
Seems like my mirroring script failed on a day or so, currently remirroring all missing movie infos, should be done in a day or so.

**Comment by galli-leo** [comment]
So I just found out my mirrororring script had an error and hence the last mirror I tried didn't work. Will try to fix this today. Should hopefully be done in 2-3 hours.

**Comment by galli-leo** [comment]
@RyanMathewson Can you try again. API still only returns 612 movies, but I would guess those aren't on TMDB.

**Comment by RyanMathewson** [comment]
That fixed it!  Thanks a ton.  My wife is super happy now :)
